### PR TITLE
Updated components landing page content

### PR DESCRIPTION
**Pull request by karypun**

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Needs to be rebased but looks good otherwise.

**Comment by daniel-ac-martin** [comment]
Probably best if I sort this out after we merge #101.

**Comment by karypun** [comment]
> Probably best if I sort this out after we merge #101.

Yes, I forgot to respond to this -  sorry I didn't know how to do the rebase :-O

**Comment by daniel-ac-martin** [comment]
I usually just do:
```shell
git pull --rebase origin master && git push -f
```

But it's possible for it to go wrong from time to time.

**Comment by karypun** [comment]
@daniel-ac-martin there was something wrong with the styling of the system on my end so I scrapped it to do a new clone and no longer have the branch. I could create a new PR instead?

**Comment by daniel-ac-martin** [comment]
I can sort it.

But if you do:
```shell
git fetch
git checkout components-landing-page
```
You should be able to get back to your branch.

**Comment by karypun** [comment]
I'll do it and let you know

**Comment by karypun** [comment]
@daniel-ac-martin think I've updated it now

**Comment by daniel-ac-martin** [comment]
Ah you've still got some of Elliots commits because we've not merged them in yet.

The rebase worked otherwise though.

**Review by daniel-ac-martin — APPROVED** [review]

**Pull request merged**
